"""四柱管线运行常量。"""

BASE_SUBTASK_TIMEOUT = 300
TIMEOUT_ESCALATION_STEP = 60
MAX_TIMEOUT_ESCALATIONS = 3
BENCHMARK_SUBTASK_TIMEOUT = 90
BENCHMARK_TIMEOUT_ESCALATIONS = 0
LLM_CALL_TIMEOUT_SECONDS = 120
CIRCUIT_BREAKER_CONSECUTIVE_FAILS = 2
BENCHMARK_REDUNDANT_BLOCK_LIMIT = 1
BENCHMARK_LOW_VALUE_SIGNAL_LIMIT = 4
BENCHMARK_SETUP_TIMEOUT_STREAK_LIMIT = 3
BENCHMARK_MAX_ITERATION_BATCHES = 20
BENCHMARK_RUSH_REMAINING_THRESHOLD = 1400
